const $=id=>document.getElementById(id);
['strength','aggression','depth','giveup'].forEach(k=>$(k)?.addEventListener('input',()=>$(k+'Out').value=$(k).value));
const boats=[1,2,3,4,5,6];
const API=(localStorage.getItem('ver2_api')||'').replace(/\/$/,'');
function rng(seed){let x=seed>>>0;return()=>{x^=x<<13;x^=x>>>17;return(x>>>0)/4294967296}}
function localSim(n=10000,front={boat:0,strength:0,aggression:50,depth:50,giveup:50,target:2},seed=20260904){const R=rng(seed),slits={},back={},methods={},top=Object.fromEntries(boats.map(b=>[b,[0,0,0]]));for(let t=0;t<n;t++){let c=[1,2,3,4,5,6];let notes=[];if(front.boat){let b=front.boat-1,target=front.target-1,s=front.strength/100,a=front.aggression/100,g=front.giveup/100;let pressure=s*(.45+.55*a),settle=1/(1+Math.exp(-(pressure+.35*(1-g)-.38)*7));if(R()<settle){let newc=Math.max(target,Math.min(b-1,target));if(newc!==b){let occ=c.indexOf(newc);if(occ>=0&&R()<.05+.22*(1-g))notes.push('抵抗→前付け不成立寄り');else{let old=c[b];c[b]=newc;if(occ>=0)c[occ]=old;notes.push(`${front.boat}号艇前付け成立`)}}}}let st=boats.map((b,i)=>.14-.01*R()+.003*(i-2));let score=boats.map((b,i)=>.15+.16*R()+.08*(i/5));if(front.boat)score[front.boat-1]+=front.strength/100*.18;let leader=score.map((v,i)=>v+.12*(1-st[i]/.2)+.08*R());let attack=leader.indexOf(Math.max(...leader));let method=['逃げ','差し','まくり','まくり差し'][Math.floor(R()*4)];if(c[attack]===1)method='逃げ';else if(R()<.35)method='差し';methods[method]=(methods[method]||0)+1;leader[attack]+=.16;let bo=boats.slice().sort((a,b)=>leader[b-1]-leader[a-1]);let slit=c.join('-');slits[slit]=(slits[slit]||0)+1;let bs=bo.join('-');back[bs]=(back[bs]||0)+1;bo.slice(0,3).forEach((b,r)=>top[b][r]++);notes.forEach(x=>methods[x]=(methods[x]||0)+1)}let rep=Object.entries(slits).sort((a,b)=>b[1]-a[1])[0],brep=Object.entries(back).sort((a,b)=>b[1]-a[1])[0];return{simulations:n,representative_start_slit:rep[0],representative_start_slit_rate:rep[1]/n,representative_back_middle:brep[0],representative_back_middle_rate:brep[1]/n,top3_rate:Object.fromEntries(boats.map(b=>[b,top[b].reduce((a,v)=>a+v,0)/n])),rank_rates:Object.fromEntries(boats.map(b=>[b,top[b].map(v=>v/n)])),decisive_method_rate:Object.fromEntries(Object.entries(methods).filter(([k])=>['逃げ','差し','まくり','まくり差し','恵まれ'].includes(k)).map(([k,v])=>[k,v/n]))}}
function current(){return{boat:+$('boat').value,strength:+$('strength').value,aggression:+$('aggression').value,depth:+$('depth').value,giveup:+$('giveup').value,target:+$('target').value}}
function render(r){$('summary').innerHTML=[['代表スタートスリット',(r.representative_start_slit||r.repSlit)],['出現率',((r.representative_start_slit_rate??r.repRate)*100).toFixed(1)+'%'],['代表バック中間',r.representative_back_middle||r.back],['出現率',((r.representative_back_middle_rate??r.backRate)*100).toFixed(1)+'%']].map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="value">${x[1]}</div></div>`).join('');let top=r.top3_rate||r.top;$('bars').innerHTML=boats.map(b=>{let v=(top[b]??top[String(b)])*100;return `<div class="bar"><div class="barTop"><span>${b}号艇</span><b>${v.toFixed(1)}%</b></div><div class="track"><div class="fill" style="width:${Math.min(100,v)}%"></div></div></div>`}).join('');$('methods').innerHTML=Object.entries(r.decisive_method_rate||r.methods||{}).sort((a,b)=>b[1]-a[1]).map(x=>`<div class="card"><div class="label">${x[0]}</div><div class="value">${(x[1]*100).toFixed(1)}%</div></div>`).join('')||'<div class="card">データなし</div>'}
async function run(){const n=10000,f=current();$('msg').textContent=API?'APIで計算中…':'ブラウザ軽量エンジンで計算中…';try{let r;if(API){let race={race_id:'web-demo',boats:boats.map(b=>({boat_no:b,exhibition_st:.15,stretch:0,accel:0,turn:0,pressure_resistance:0,attack:0,defend:0,psychology:0,start_quality:0})),wind:.2,wave:.1,base_entry:[1,2,3,4,5,6]};let res=await fetch(API+'/simulate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({race,simulations:n,fronting:f.boat?[{boat_no:f.boat,strength:f.strength,start_aggression:f.aggression,depth:f.depth,give_up:f.giveup,target_course:f.target}]:[]})});if(!res.ok)throw new Error(await res.text());r=await res.json()}else r=localSim(n,f);render(r);$('msg').textContent='計算完了';$('simBadge').textContent=n.toLocaleString()+' samples'}catch(e){$('msg').textContent='API接続失敗。ローカルで再計算します。';render(localSim(n,f))}}
$('run').onclick=run;$('compare').onclick=()=>{let conds=[['なし',{boat:0}],['中',{boat:3,strength:50,aggression:60,depth:50,giveup:50,target:2}],['強め',{boat:3,strength:80,aggression:70,depth:65,giveup:30,target:2}],['強・深・粘り',{boat:3,strength:95,aggression:90,depth:90,giveup:10,target:2}]];let rs=conds.map(([name,c],i)=>[name,localSim(10000,c,20260904+i)]);$('comparison').innerHTML='<table><thead><tr><th>条件</th><th>代表スリット</th>'+boats.map(b=>`<th>${b}号艇</th>`).join('')+'</tr></thead><tbody>'+rs.map(([n,r])=>`<tr><td>${n}</td><td>${r.representative_start_slit}</td>${boats.map(b=>`<td>${(r.top3_rate[b]*100).toFixed(1)}%</td>`).join('')}</tr>`).join('')+'</tbody></table>';$('msg').textContent='4条件比較完了'};run();


let liveRaceData=null;
function liveRender(d){liveRaceData=d; const ok=d.status==='ready_for_simulation'; $('liveStatus').textContent=(d.event_name||'浜名湖')+' / '+d.race_no+'R / '+(ok?'実戦シミュレーション可能':d.status); $('liveBoats').innerHTML=(d.boats||[]).map(b=>`<div class="liveBoat"><b>${b.boat_no}号艇</b> ${b.racer_name||'—'} <span>${b.racer_class||''}</span> <small>展示ST ${b.exhibition_st??'未取得'} / 展示 ${b.exhibition_time??'未取得'}</small></div>`).join('') || '<div>艇データなし</div>'; }
async function livePrepare(){const api=(localStorage.getItem('ver2_api')||'').replace(/\/$/,''); if(!api){$('liveMsg').textContent='先にAPI URLを設定してください';return;} const date=$('liveDate').value,race=+$('liveRace').value; $('liveMsg').textContent='公式データ取得中…'; try{const r=await fetch(`${api}/live/prepare?date=${date}&race_no=${race}`); if(!r.ok)throw new Error(await r.text()); liveRender(await r.json()); $('liveMsg').textContent='取得完了';}catch(e){$('liveMsg').textContent='取得失敗: '+e.message}}
async function liveSim(){const api=(localStorage.getItem('ver2_api')||'').replace(/\/$/,''); if(!api||!liveRaceData){$('liveMsg').textContent='先に公式データを取得してください';return;} $('liveMsg').textContent='実戦MC計算中…'; try{const f=current(); const r=await fetch(api+'/live/simulate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({race:liveRaceData,simulations:10000,seed:20260904,fronting:f.boat?[{boat_no:f.boat,strength:f.strength,start_aggression:f.aggression,depth:f.depth,give_up:f.giveup,target_course:f.target}]:[]})}); if(!r.ok)throw new Error(await r.text()); const x=await r.json(); render(x.result); $('liveMsg').textContent='実戦シミュレーション完了 / prediction #'+x.prediction_id;}catch(e){$('liveMsg').textContent='計算失敗: '+e.message}}
$('livePrepare')?.addEventListener('click',livePrepare); $('liveSim')?.addEventListener('click',liveSim);
