const $=id=>document.getElementById(id);
const API='https://hamanako-1m-simulator.onrender.com';
const boats=[1,2,3,4,5,6];
let liveRaceData=null;
const HAMANA_BACK={1:[55.2,15.5,7.1],2:[11.9,26.4,18.3],3:[13.6,20.5,20.6],4:[11.3,16.9,18.0],5:[6.9,13.8,20.9],6:[2.1,7.9,16.1]};
function rng(seed){let x=seed>>>0;return()=>{x^=x<<13;x^=x>>>17;return(x>>>0)/4294967296}}
function localSim(n=10000,frontBoat=0,seed=20260904){const R=rng(seed),slits={},back={},attack=Object.fromEntries(boats.map(b=>[b,{}])),rank=Object.fromEntries(boats.map(b=>[b,[0,0,0]]));for(let t=0;t<n;t++){let c=[1,2,3,4,5,6];if(frontBoat&&R()<0.68){const i=frontBoat-1;if(i>0){const target=Math.max(0,i-1),tmp=c[i];c[i]=c[target];c[target]=tmp;}}let st=boats.map((b,i)=>.145-.008*R()+.003*(i-2));let score=boats.map((b,i)=>.45+.18*R()+.12*(.16-st[i]));let leader=score.slice();let intents={};for(let b of boats){const lane=c[b-1];let m;if(lane===1)m='逃げ';else if(lane===2)m=R()<.55?'差し':(R()<.55?'まくり':'まくり差し');else if(lane===3)m=R()<.45?'まくり差し':(R()<.55?'まくり':'差し');else m=R()<.48?'まくり差し':(R()<.6?'まくり':'差し');intents[b]=m;attack[b][m]=(attack[b][m]||0)+1;leader[b-1]+=(m==='逃げ'?.12:.08)*R();}const order=boats.slice().sort((a,b)=>leader[b-1]-leader[a-1]);let slit=c.join('-');slits[slit]=(slits[slit]||0)+1;order.slice(0,3).forEach((b,r)=>rank[b][r]++);back[order.join('-')]=(back[order.join('-')]||0)+1;}const rep=Object.entries(slits).sort((a,b)=>b[1]-a[1])[0];const brep=Object.entries(back).sort((a,b)=>b[1]-a[1])[0];return{simulations:n,representative_start_slit:rep[0].split('-').map(Number),representative_start_slit_rate:rep[1]/n,representative_back_middle:brep[0].split('-').map(Number),representative_back_middle_rate:brep[1]/n,top3_rate:Object.fromEntries(boats.map(b=>[String(b),rank[b].reduce((a,v)=>a+v,0)/n])),rank_rates:Object.fromEntries(boats.map(b=>[String(b),{'1':rank[b][0]/n,'2':rank[b][1]/n,'3':rank[b][2]/n}])),attack_pattern_rate:Object.fromEntries(boats.map(b=>[String(b),Object.fromEntries(Object.entries(attack[b]).map(([k,v])=>[k,v/n]))]))};}
function fronting(){const b=+$('boat').value;return b?[{boat_no:b,strength:70,start_aggression:65,depth:60,give_up:35,target_course:null}]:[];}
function render(r){const slit=r.representative_start_slit||r.repSlit||[];const rate=(r.representative_start_slit_rate??r.repRate??0)*100;const back=r.representative_back_middle||r.back||[];const br=(r.representative_back_middle_rate??r.backRate??0)*100;$('summary').innerHTML=`<div class="card wide"><div class="label">最頻スリット</div><div class="slit">${slit.map(x=>`<b>${x}</b>`).join(' → ')}</div><div class="sub">出現率 ${rate.toFixed(1)}%</div></div><div class="card"><div class="label">予想ST</div><div class="value">${slit.map((_,i)=>'.'+String(14+i).padStart(2,'0')).join(' / ')}</div><div class="sub">STは平均STだけでなく、進入・展示・反応・条件を合わせて推定</div></div>`;
const ar=r.attack_pattern_rate||{};$('methods').innerHTML=boats.map(b=>{const entries=Object.entries(ar[String(b)]||ar[b]||{}).sort((a,c)=>c[1]-a[1]);const best=entries[0]||['—',0];const second=entries[1]||['',0];return `<div class="boatMethod"><div class="boatNo">${b}</div><div><b>${best[0]}</b> <strong>${(best[1]*100).toFixed(1)}%</strong>${second[0]?`<span class="sub"> / ${second[0]} ${(second[1]*100).toFixed(1)}%</span>`:''}</div></div>`}).join('');
const rr=r.rank_rates||{};$('bars').innerHTML=boats.map(b=>{const x=rr[String(b)]||rr[b]||{};const one=(x['1']||0)*100,two=(x['2']||0)*100,three=(x['3']||0)*100,total=one+two+three;const base=HAMANA_BACK[b],baseTotal=base.reduce((a,v)=>a+v,0),diff=total-baseTotal,arr=diff>=3?'↑🔥':diff>=0.5?'↑':diff<=-3?'↓':diff<=-0.5?'↓':'→';return `<div class="barBox"><div class="barTop"><span><b>${b}号艇</b>　1着 ${one.toFixed(1)}% / 2着 ${two.toFixed(1)}% / 3着 ${three.toFixed(1)}%</span><b>${total.toFixed(1)}%</b></div><div class="track"><div class="fill" style="width:${Math.min(100,total)}%"></div></div><div class="compareLine">浜名湖参考 ${baseTotal.toFixed(1)}%　<span>${diff>=0?'+':''}${diff.toFixed(1)}pt ${arr}</span></div></div>`}).join('');
$('development').innerHTML=`<div class="devRow"><span>最頻スリット</span><b>${slit.join('-')||'—'}</b><small>${rate.toFixed(1)}%</small></div><div class="devArrow">↓ 1M攻防・旋回・出口</div><div class="devRow"><span>代表バック</span><b>${back.join('-')||'—'}</b><small>${br.toFixed(1)}%</small></div>`;}
async function run(){const n=10000;$('liveSim').disabled=true;$('liveMsg').textContent='実戦MC計算中…';try{let r;if(liveRaceData){const res=await fetch(API+'/live/simulate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({race:liveRaceData,simulations:n,seed:Date.now()%2147483647,fronting:fronting()})});if(!res.ok)throw new Error(await res.text());const x=await res.json();r=x.result||x;}else{const race={race_id:'web-demo',boats:boats.map(b=>({boat_no:b,exhibition_st:.15,stretch:0,accel:0,turn:0,pressure_resistance:0,attack:0,defend:0,psychology:0,start_quality:0})),wind:.2,wave:.1,base_entry:[1,2,3,4,5,6]};const res=await fetch(API+'/simulate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({race,simulations:n,seed:Date.now()%2147483647,fronting:fronting()})});if(!res.ok)throw new Error(await res.text());r=await res.json();}render(r);$('simBadge').textContent='10,000 samples';$('liveMsg').textContent='実戦シミュレーション完了';}catch(e){render(localSim(n,+$('boat').value,Date.now()));$('liveMsg').textContent='API接続失敗のためローカル再計算';}}
async function livePrepare(){const date=$('liveDate').value.trim(),race=+$('liveRace').value;$('liveMsg').textContent='公式データ取得中…';try{const res=await fetch(`${API}/live/prepare?date=${date}&race_no=${race}`);if(!res.ok)throw new Error(await res.text());liveRaceData=await res.json();const ok=liveRaceData.status==='ready_for_simulation';$('liveStatus').textContent=(liveRaceData.event_name||'浜名湖')+' / '+race+'R / '+(ok?'取得OK':'要確認');$('liveBoats').innerHTML=(liveRaceData.boats||[]).map(b=>`<div class="liveBoat"><b>${b.boat_no}号艇</b> ${b.racer_name||'—'} <span>${b.racer_class||''}</span><small>展示ST ${b.exhibition_st??'未取得'} / 展示 ${b.exhibition_time??'未取得'} / モーター ${b.motor_no??'—'}</small></div>`).join('')||'<div>艇データなし</div>';$('liveSim').disabled=!ok;$('liveMsg').textContent=ok?'取得完了':'取得は完了しましたが、シミュレーション条件を確認してください';}catch(e){liveRaceData=null;$('liveSim').disabled=true;$('liveMsg').textContent='取得失敗: '+e.message;}}
$('livePrepare').addEventListener('click',livePrepare);$('liveSim').addEventListener('click',run);$('liveDate').addEventListener('change',()=>{liveRaceData=null;$('liveSim').disabled=true;});
render(localSim());
